services:
  hermes:
    image: ghcr.io/brendon-hablutzel/hermes:latest
    # build: .
    ports:
      - "8080:8080"
    env_file: 
      - .env
    volumes:
      - ./projects.json:/app/projects.json
